HOUR_COLUMN_NAME = 'hr'
DAY_OF_WEEK_COLUMN_NAME = 'dow'
FREQUENCY_COLUMN_NAME = 'fq'
RECENCY_COLUMN_NAME = 'recency'
INVIEW_FREQUENCY_COLUMN_NAME = 'inview_fq'
INVIEW_RECENCY_COLUMN_NAME = 'inview_recency'
ELAPSED_TIME_RE_TARGET_COLUMN_NAME = 'elapsed_time_rt'
IS_RE_TARGET_ANY_COLUMN_NAME = 'is_rt_any'
IS_SAME_DOMAIN_COLUMN_NAME = 'is_same_domain'
CREATIVE_TYPE_COLUMN_NAME = 'creative_type'
OS_COLUMN_NAME = 'os'
PROBABILITY_MAN_COLUMN_NAME = 'prob_man'
CTR_USER_COLUMN_NAME = 'ctr_user'
INVIEW_RATIO_COLUMN_NAME = 'inview_ratio'
CTR_SLOT_COLUMN_NAME = 'ctr_slot'
INVIEW_CTR_SLOT_COLUMN_NAME = 'iv_ctr_slot'
SLOT_CATEGORY_COLUMN_NAME = 'slot_category'
SLOT_SITE_TYPE_COLUMN_NAME = 'slot_site_type'
CTR_SPONSOR_SLOT_COLUMN_NAME = 'ctr_sp_slot'
INVIEW_CTR_SPONSOR_SLOT_COLUMN_NAME = 'iv_ctr_sp_slot'

SPONSOR_ID_COLUMN_NAME = 'sponsor_id'
SLOT_ID_COLUMN_NAME = 'slot_id'
IS_CLICK_COLUMN_NAME = 'is_click'

FEATURES_COLUMNS_NAMES = [
    HOUR_COLUMN_NAME,
    DAY_OF_WEEK_COLUMN_NAME,
    # FREQUENCY_COLUMN_NAME,
    # RECENCY_COLUMN_NAME,
    # INVIEW_FREQUENCY_COLUMN_NAME,
    # INVIEW_RECENCY_COLUMN_NAME,
    ELAPSED_TIME_RE_TARGET_COLUMN_NAME,
    IS_RE_TARGET_ANY_COLUMN_NAME,
    IS_SAME_DOMAIN_COLUMN_NAME,
    CREATIVE_TYPE_COLUMN_NAME,
    OS_COLUMN_NAME,
    PROBABILITY_MAN_COLUMN_NAME,
    CTR_USER_COLUMN_NAME,
    INVIEW_RATIO_COLUMN_NAME,
    CTR_SLOT_COLUMN_NAME,
    INVIEW_CTR_SLOT_COLUMN_NAME,
    SLOT_CATEGORY_COLUMN_NAME,
    SLOT_SITE_TYPE_COLUMN_NAME,
    CTR_SPONSOR_SLOT_COLUMN_NAME,
    INVIEW_CTR_SPONSOR_SLOT_COLUMN_NAME
]